### ISSUE TITLE
config  not working

### ISSUE THREAD

**Issue by HManzano1012** [mmsaeed509/bspwm-dots#3]
hey man nice job with the rice,
i am kinda new with this stuff and I wanted to try your dotfiles, but I dont know if I did something wrong but the configuration didnt work in my arch  installation. 
If you have the chance to help me I would appreciate it so much.

Keep the good work man.

**Comment by mmsaeed509** [comment]
what's the problem?

**Comment by HManzano1012** [comment]
well I am not getting the style on the bar at all and  if I try to use any shortcut i get 
  --The following errors were detected when starting rofi
-----error while  parsing theme 

i dont know what could be happening, I installed all the packages with the _install arch packages_ script and I tried with a 
new arch installation.

**Comment by mmsaeed509** [comment]
to launch `polybar -q main -c <config_dir>`
e.g `polybar -q main -c ~/.config/bspwm/polybar/valorant/config`  launch VALORANT polybar
OR `polybar -q main -c ~/.config/bspwm/polybar/JapaneseCity/config`  launch Japanese City polybar


for `rofi` give a screenshot

**Comment by HManzano1012** [comment]
OK, I'll give it a try

**Comment by Giygas** [comment]
Hi, I'm having the same problem, I got this error and I can't use anything, I can't even use the power off key.

I'll put a photo of the error because I can't log in with bspwm

But the bar does work
![PXL_20220804_020406905](https://user-images.githubusercontent.com/2224288/182750027-3abf2658-6cc6-461e-847b-fb58682b5bf6.jpg)

EDIT: 
Well, I managed to make Alacritty work, so I'm testing a bit more, it looks like there's some problem with the color parsing or something. Some polybars works better than others

For example, this is the hack theme
![Screenshot_2022-08-04-00-50-36_1920x1080](https://user-images.githubusercontent.com/2224288/182759758-75120360-f72f-490e-9d3a-261b9eef9756.png)

Everything gives errors or doesn't work except for the widget to change theme and you can see Alacrity is having problems to parse colors too

And this is the BlackArch theme a bit buggy

![Screenshot_2022-08-04-00-44-25_1920x1080](https://user-images.githubusercontent.com/2224288/182760004-1ca321dd-dc27-4200-b86c-0555c95a6a4c.png)

I noticed here the colors are set in the theme config, when in the hack theme there are no colors set but works better

**Comment by mmsaeed509** [comment]
for ROFI I think it's a parser error, but  you can change the color as shown in the video

https://user-images.githubusercontent.com/62524855/182762356-ab502e6c-1207-4e80-8199-3de7de9437d5.mp4

do for all files.rasi

to launch `polybar -q main -c <config_dir>`
e.g `polybar -q main -c ~/.config/bspwm/polybar/valorant/config`  launch VALORANT polybar
OR `polybar -q main -c ~/.config/bspwm/polybar/JapaneseCity/config`  launch Japanese City polybar

for polybar color file, you can change it in the config file 
e.g VALORANT polybar edit `~/.config/bspwm/polybar/valorant/config`

![Screenshot_2022-08-04-06-27-19_3840x1080](https://user-images.githubusercontent.com/62524855/182763164-55aa3ab7-89b5-41f0-9a20-849516ea38fe.png)

this is a color scheme location `include-file = ~/.config/bspwm/polybar/valorant/colors` 
you can create your own color scheme file and set its location

**Comment by Giygas** [comment]
Yes, thank you, but that'll take a lot of time so I decided to look a bit through the code and I found that the xrdb -query was clearing the colors.rasi because I haven't had a .Xresources set, so I downloaded a theme for that and it's all good now

So for the OP,  you should have ~/.Xresources file with some colors so you don't get the parse theme error

**Comment by mmsaeed509** [comment]
OK!
thanks for helping!

**Comment by HManzano1012** [comment]
> Yes, thank you, but that'll take a lot of time so I decided to look a bit through the code and I found that the xrdb -query was clearing the colors.rasi because I haven't had a .Xresources set, so I downloaded a theme for that and it's all good now
> 
> So for the OP, you should have ~/.Xresources file with some colors so you don't get the parse theme error

Can you share your Xresources file?

**Comment by mmsaeed509** [comment]
`.Xresource` in misc dir [.Xresource](https://github.com/mmsaeed509/bspwm-dots/blob/master/misc/.Xresources)
